[context.deploy-preview.environment]
  NODE_VERSION = '14.17.3'

[build]
    publish = "dist/"
    command = '''
    mkdir dist
    echo 'User-agent: *' >> dist/robots.txt
    echo 'Disallow: /' >> dist/robots.txt
    cp public/* dist/

    mv 2019/public dist/2019
    cd 2021 && npm ci
    pwd && ls node_modules
    ls node_modules/gatsby-plugin-styled-components
    npm run build -- --prefix-paths --verbose && mv public ../dist/2021
    '''
