[context.deploy-preview.environment]
  NODE_VERSION = '14.17.3'
  NODE_ENV = 'development'

[build]
    publish = "dist/"
    command = '''
    mkdir dist
    echo 'User-agent: *' >> dist/robots.txt
    echo 'Disallow: /' >> dist/robots.txt
    cp public/* dist/

    mv 2019/public dist/2019
    mv 2021/public dist/2021
    cd 2022 && npm ci && npm run build -- --prefix-paths --verbose && mv public ../dist/2022
    '''
