[context.deploy-preview.environment]
  NODE_VERSION = '18.14.0'
  NODE_ENV = 'development'

[build]
    publish = "dist/"
    command = '''
    mkdir dist
    echo 'User-agent: *' >> dist/robots.txt
    echo 'Disallow: /' >> dist/robots.txt
    cp public/* dist/

    mv 2019/public dist/2019
    mv 2021/public dist/2021
    mv 2022/public dist/2022
    cd 2023 && npm ci --legacy-peer-deps && npm run build -- --prefix-paths --verbose && mv public ../dist/2023
    '''
