workflows:
  version: 2
  test_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "2019/package-lock.json" }}
      - run: mkdir dist
      - run: cp public/* dist/
      - run: mv 2019/public dist/2019
      - run: git config --global user.name "CircleCI deploy"
      - run: git config --global user.email "circleci@example.com"
      - run: npx gh-pages --dist dist --message "[skip ci] Updates"
