name: CI

on: [pull_request]

jobs:
  build_2023:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: 2023/package-lock.json
      - run: cd 2023 && npm ci --legacy-peer-deps
      - run: cd 2023 && npm run build -- --prefix-paths
  test_2023:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: 2023/package-lock.json
      - run: cd 2023 && npm ci --legacy-peer-deps
      - run: cd 2023 && npm test
