name: CI

on: [pull_request]

jobs:
  build_2022:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: cd 2022 && npm ci
      - run: cd 2022 && npm run build -- --prefix-paths
  test_2022:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: cd 2022 && npm ci
      - run: cd 2022 && npm test
